from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("assets", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("symbol", sa.String(32), nullable=False, unique=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("decimals", sa.Integer(), nullable=False, server_default="18"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("markets", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("symbol", sa.String(40), nullable=False, unique=True), sa.Column("base_asset_id", sa.Integer(), sa.ForeignKey("assets.id"), nullable=False), sa.Column("quote_asset_id", sa.Integer(), sa.ForeignKey("assets.id"), nullable=False), sa.Column("price_precision", sa.Integer(), nullable=False, server_default="8"), sa.Column("quantity_precision", sa.Integer(), nullable=False, server_default="8"), sa.Column("min_quantity", sa.Numeric(36,18), nullable=False, server_default="0"), sa.Column("min_notional", sa.Numeric(36,18), nullable=False, server_default="0"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("accounts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("asset_id", sa.Integer(), sa.ForeignKey("assets.id"), nullable=False), sa.Column("available_balance", sa.Numeric(36,18), nullable=False, server_default="0"), sa.Column("locked_balance", sa.Numeric(36,18), nullable=False, server_default="0"), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("user_id","asset_id",name="uq_account_user_asset"))
    op.create_table("orders", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("market_id", sa.Integer(), sa.ForeignKey("markets.id"), nullable=False), sa.Column("side", sa.Enum("BUY","SELL",name="orderside"), nullable=False), sa.Column("type", sa.Enum("MARKET","LIMIT",name="ordertype"), nullable=False), sa.Column("status", sa.Enum("PENDING","OPEN","PARTIALLY_FILLED","FILLED","CANCELLED","REJECTED",name="orderstatus"), nullable=False), sa.Column("quantity", sa.Numeric(36,18), nullable=False), sa.Column("filled_quantity", sa.Numeric(36,18), nullable=False, server_default="0"), sa.Column("limit_price", sa.Numeric(36,18)), sa.Column("average_fill_price", sa.Numeric(36,18)), sa.Column("reserved_amount", sa.Numeric(36,18), nullable=False, server_default="0"), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.Column("cancelled_at", sa.DateTime()))
    op.create_table("trades", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("order_id", sa.Integer(), sa.ForeignKey("orders.id"), nullable=False), sa.Column("market_id", sa.Integer(), sa.ForeignKey("markets.id"), nullable=False), sa.Column("quantity", sa.Numeric(36,18), nullable=False), sa.Column("price", sa.Numeric(36,18), nullable=False), sa.Column("quote_amount", sa.Numeric(36,18), nullable=False), sa.Column("fee", sa.Numeric(36,18), nullable=False, server_default="0"), sa.Column("executed_at", sa.DateTime(), nullable=False))
    op.create_table("transactions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("account_id", sa.Integer(), sa.ForeignKey("accounts.id"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("asset_id", sa.Integer(), sa.ForeignKey("assets.id"), nullable=False), sa.Column("type", sa.Enum("DEPOSIT","WITHDRAWAL","ORDER_RESERVATION","ORDER_RELEASE","TRADE_DEBIT","TRADE_CREDIT","FEE",name="transactiontype"), nullable=False), sa.Column("amount", sa.Numeric(36,18), nullable=False), sa.Column("balance_before", sa.Numeric(36,18), nullable=False), sa.Column("balance_after", sa.Numeric(36,18), nullable=False), sa.Column("reference_type", sa.String(40)), sa.Column("reference_id", sa.String(64)), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("refresh_tokens", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("token_hash", sa.String(255), nullable=False, unique=True), sa.Column("expires_at", sa.DateTime(), nullable=False), sa.Column("revoked_at", sa.DateTime()), sa.Column("replaced_by_id", sa.Integer(), sa.ForeignKey("refresh_tokens.id")), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("portfolio_snapshots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("total_value", sa.Numeric(36,18), nullable=False), sa.Column("realized_pnl", sa.Numeric(36,18), nullable=False), sa.Column("unrealized_pnl", sa.Numeric(36,18), nullable=False), sa.Column("captured_at", sa.DateTime(), nullable=False))

def downgrade() -> None:
    for table in ["portfolio_snapshots","refresh_tokens","transactions","trades","orders","accounts","markets","assets","users"]:
        op.drop_table(table)
