import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";
type Market={symbol:string;price:string}; type Account={asset:string;available_balance:string}; type Order={id:number;market:string;side:string;status:string;quantity:string};
const API=import.meta.env.VITE_API_URL||"http://localhost:8000/api/v1";
async function request(path:string,options:RequestInit={}){const token=localStorage.getItem("tradeflow_access");const h=new Headers(options.headers);h.set("Content-Type","application/json");if(token)h.set("Authorization","Bearer "+token);const r=await fetch(API+path,{...options,headers:h});if(!r.ok)throw new Error((await r.json().catch(()=>null))?.detail||"Request failed");return r.json()}
function App(){
 const [token,setToken]=useState(localStorage.getItem("tradeflow_access"));const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [markets,setMarkets]=useState<Market[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [selected,setSelected]=useState("BTC/USDT");const [side,setSide]=useState("BUY");const [quantity,setQuantity]=useState("0.001");const [message,setMessage]=useState("");
 async function load(){const[m,a,o]=await Promise.all([request("/markets"),request("/account"),request("/orders")]);setMarkets(m);setAccounts(a);setOrders(o)}
 useEffect(()=>{if(token)load().catch(e=>setMessage(e.message))},[token]);
 async function auth(path:string){try{const d=await request(path,{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("tradeflow_access",d.access_token);localStorage.setItem("tradeflow_refresh",d.refresh_token);setToken(d.access_token);setMessage("Authenticated.")}catch(e){setMessage((e as Error).message)}}
 async function order(){try{await request("/orders",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({market:selected,side,type:"MARKET",quantity})});setMessage("Order submitted.");await load()}catch(e){setMessage((e as Error).message)}}
 if(!token)return <main className="auth"><section className="card auth-card"><span className="eyebrow">TRADEFLOW</span><h1>Paper trading, built properly.</h1><p>FastAPI + MySQL + Redis + React. No real funds.</p><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><div className="actions"><button onClick={()=>auth("/login")}>Sign in</button><button className="ghost" onClick={()=>auth("/register")}>Create account</button></div>{message&&<small>{message}</small>}</section></main>;
 const balance=accounts.find(a=>a.asset==="USDT");
 return <main className="app"><header><div><span className="eyebrow">TRADEFLOW</span><h1>Trading dashboard</h1></div><button className="ghost" onClick={()=>{localStorage.clear();setToken(null)}}>Sign out</button></header><section className="stats"><div className="card"><span>Available USDT</span><strong>{Number(balance?.available_balance||0).toLocaleString()}</strong></div><div className="card"><span>Markets</span><strong>{markets.length}</strong></div><div className="card"><span>Open orders</span><strong>{orders.filter(o=>["OPEN","PARTIALLY_FILLED"].includes(o.status)).length}</strong></div></section><section className="grid"><div className="card"><div className="section-title"><h2>Markets</h2><span>Paper prices</span></div>{markets.map(m=><button className={selected===m.symbol?"market active":"market"} key={m.symbol} onClick={()=>setSelected(m.symbol)}><span>{m.symbol}</span><strong>{Number(m.price).toLocaleString()}</strong></button>)}</div><div className="card"><div className="section-title"><h2>Place order</h2><span>{selected}</span></div><div className="tabs"><button className={side==="BUY"?"active":""} onClick={()=>setSide("BUY")}>Buy</button><button className={side==="SELL"?"active":""} onClick={()=>setSide("SELL")}>Sell</button></div><label>Quantity<input value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><button onClick={order}>Place market order</button>{message&&<small>{message}</small>}</div></section><section className="card"><div className="section-title"><h2>Recent orders</h2><span>Latest 100</span></div><div className="table">{orders.map(o=><div className="row" key={o.id}><span>#{o.id} {o.market}</span><span>{o.side}</span><span>{o.quantity}</span><span>{o.status}</span></div>)}</div></section></main>
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
